### ISSUE TITLE
Fix external dependencies by using VisaInstrument

### ISSUE THREAD

**Issue by reneotten** [qutech/Qcodes#2]
### Steps to reproduce
1. Import Qcodes
2. Import DecaDAC

### Expected behaviour
Regular Import of DecaDac

### Actual behaviour
Error since "serial" module not part of dependencies

### Suggested Fix
Use the build in VisaInstrument, no need to add further dependencies at this point

### System
**operating system**
WIN64

**qcodes branch**
feature/FZJ_DecaDAC_driver

**qcodes commit**
8922738067f794738ab164ac2ebce13db808a771

**Comment by lankes-fzj** [comment]
The Decadac class now derives from VisaInstrument and uses its methods for the hardware communication. The serial package is not used anymore.

@reneotten Please try if the driver is working now so that the issue can be closed.
