### ISSUE TITLE
Map measurement windows to multiple outputs

### ISSUE THREAD

**Issue by qutech-lab** [qutech/Qcodes#5]
Let's say I have the measurement window 'a'. How do I measure on multiple inputs?

Is
```python
qpt_awg.measurement_mapping.set({'a' :[ 'ATS_C', 'ATS_D']})
```
possible?

**Comment by lankes-fzj** [comment]
Yes, it is possible, but not as you try it.

The `measurement_mapping` only accepts one-to-one mappings. You have to do it in the setup of the dac.
For example:
```
qpt_awg.measurement_mapping.set({'a' : 'ATS_CD'})
# ...
qpt_dac.set_measurement('ATS_CD', [MeasurementMask(ats_card, 'C'),
                                   MeasurementMask(ats_card, 'D')])
```
